name: "v1.11.x: release"

on:
  push:
    tags:
      - 1.11.**

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
      discussions: write
    uses: ./.github/workflows/template-release.yml
    secrets: inherit
    with:
      platforms: linux/amd64,linux/arm64
      directory: v1.11.x
