name: "v1.11.x: build"

on:
  push:
    branches:
      - master
    paths:
      - v1.11.x/**

  pull_request:
    branches:
      - master
    paths:
      - v1.11.x/**

jobs:
  test:
    name: Test
    uses: ./.github/workflows/template-build.yml
    with:
      platforms: linux/amd64,linux/arm64
      directory: v1.11.x
